version: '2'
services:
  mysql:
    #build:
    #  context: ./mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypass'
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    command: httpd -d /etc/httpd/ -DFOREGROUND
    ports:
      - '80:80'
    volumes:
     # - ./html:/var/www/html
     - ./firstApp:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mydb
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypass
    links:
      - mysql
volumes:
  db:

